// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGrL7Kou9rwC57xj1H6Qk3kR-Ji4FC5zc',
    appId: '1:765163980465:web:9b3bf94a7d3a5174b2c490',
    messagingSenderId: '765163980465',
    projectId: 'pawfect-match-39bb3',
    authDomain: 'pawfect-match-39bb3.firebaseapp.com',
    storageBucket: 'pawfect-match-39bb3.appspot.com',
    measurementId: 'G-PW07CDTTHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlRd4npLrQkYGHMPCh3OdAHUmegTPPUQ',
    appId: '1:765163980465:android:f29016069582f4c1b2c490',
    messagingSenderId: '765163980465',
    projectId: 'pawfect-match-39bb3',
    storageBucket: 'pawfect-match-39bb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdz_puZAzGKFWzAQ5u6dBtYY-ULZ9AE8w',
    appId: '1:765163980465:ios:de4dfa907cb645ffb2c490',
    messagingSenderId: '765163980465',
    projectId: 'pawfect-match-39bb3',
    storageBucket: 'pawfect-match-39bb3.appspot.com',
    androidClientId: '765163980465-4btt54dak8chq6usgu2a0g4ob3t77n61.apps.googleusercontent.com',
    iosClientId: '765163980465-c3qlrepqa9vml65q4m4m8mmuu8tq47b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawfectMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdz_puZAzGKFWzAQ5u6dBtYY-ULZ9AE8w',
    appId: '1:765163980465:ios:e21fa1169874852cb2c490',
    messagingSenderId: '765163980465',
    projectId: 'pawfect-match-39bb3',
    storageBucket: 'pawfect-match-39bb3.appspot.com',
    androidClientId: '765163980465-4btt54dak8chq6usgu2a0g4ob3t77n61.apps.googleusercontent.com',
    iosClientId: '765163980465-6vm13eaeq5v2vt47bb7q20bf5llql69m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawfectMatch.RunnerTests',
  );
}
